# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'API Documentation for your project'
            version: '1.0.0'
    areas:
        default:
            path_patterns:
                - '^/api'
            with_annotation: true
