# config/services.yaml

parameters:
    jwt_secret: '%env(JWT_SECRET)%'

services:
    # Autowire your JwtService
    App\Service\JwtService:
        arguments:
            $jwtSecret: '%jwt_secret%'
